more bug fixing and improvement
autopticio/open-webui pull request #14
Opened 2024-11-14 15:09 UTC by jereolivieri

2024-11-14 15:19 UTC, fdiazaguirre requested changes
Needs more work!

2024-11-14 15:19 UTC, fdiazaguirre commented on src/lib/apis/autoptic/index.ts
> +	if (endpoint_id !== '' && serverURL !== '') {
@jereolivieri deberías hacer una validación más sofisticada utilizando una RegEx. 
```suggestion
	if (typeof endpoint_id === 'string' && endpoint_id.trim() !== '' &&
    typeof serverURL === 'string' && serverURL.trim() !== '') {
    // Your code here
}

function isValidServerUrl(url) { const serverUrlRegex = /^(https?:\/\/)?([a-zA-Z0-9\-\.]+)(\.[a-zA-Z]{2,})(:[0-9]{1,5})?(\/.*)?$/; return serverUrlRegex.test(url); }
```

2024-11-14 15:19 UTC, fdiazaguirre commented on src/lib/apis/autoptic/index.ts
> +				return null;
re-throw the original exception, and stop with the overriding [behavior anti-pattern](https://stackoverflow.com/questions/24623484/exception-handling-anti-patterns-why-log-and-return-null-is-an-anti-pattern)!

2024-11-14 15:19 UTC, fdiazaguirre commented on src/lib/apis/autoptic/index.ts
> +		return []
if an empty array is the default value, initialize the res variable with that and reduce the [cyclomatic complexity](https://www.geeksforgeeks.org/cyclomatic-complexity/#)!

2024-11-14 15:19 UTC, fdiazaguirre commented on src/lib/apis/autoptic/index.ts
> +	if (endpoint_id !== '' && serverURL !== '') {
ditto

2024-11-14 15:19 UTC, fdiazaguirre commented on src/lib/apis/autoptic/index.ts
> +				return null;
ditto

2024-11-14 15:19 UTC, fdiazaguirre commented on src/lib/apis/autoptic/index.ts
> +		return []
ditto

2024-11-14 15:29 UTC, jereolivieri commented on src/lib/apis/autoptic/index.ts
> +	if (endpoint_id !== '' && serverURL !== '') {
The formatting and validation of the URL was done in another part of the application. So, is not necessary here.

2024-11-14 15:47 UTC, jereolivieri commented on src/lib/apis/autoptic/index.ts
> +	if (endpoint_id !== '' && serverURL !== '') {
it’s not exactly the same regex validation, and due to how the code was previously written, it needs to be done this way

2024-11-15 19:50 UTC, fdiazaguirre approved these changes
LGTM

2024-11-15 20:03 UTC, merged